title: Mississippi Coast Homeschool Concert Band
logo: /assets/images/logo.png
hero: /assets/images/hero.jpg
email: contact@yourband.org
url: "https://yourusername.github.io"
baseurl: "/mchcb-site"
theme: null
