title: Mississippi Coast Homeschool Concert Band
logo: /assets/images/logo.png
hero: /assets/images/hero.jpg
email: contact@yourband.org
baseurl: ""          # leave blank unless using a subfolder
url: "https://Monster52.github.io"
theme: null
